version: '3.0'
volumes:
  node_modules:

services:
  app:
    image: node:4-alpine
    command: yarn run test-app
    working_dir: '/app'
    environment:
      LANG: en_US.UTF-8
      FORCE_COLOR: 'true'
    volumes:
      - './:/app/'
      - node_modules:/app/node_modules/
    ports:
      - '9838:9838'
